### ISSUE TITLE
24. User story: Contact Site Admin

### ISSUE THREAD

**Issue by lienebriede** [lienebriede/jurtaka-hiking-forum#30]
As a **Registered Site User** I can **fill in the contact form** so that **I can contact the forum admin**

## Acceptance Criteria:

- I can find a contact form on the site
- I can fill in the form and send it to the admin
- After sending the form, I receive a message that the form has been sent
- I can choose a reason for contacting the admin

## Tasks:

- [ ] Add a Contact model
- [ ] Add views and update urls
- [ ] Create a template, style
