### ISSUE TITLE
21. User story: Edit and delete posts

### ISSUE THREAD

**Issue by lienebriede** [lienebriede/jurtaka-hiking-forum#32]
As a **Registered Site User** I can **update and delete my posts** so that **I can update the content of my post or remove posts that are not relevant**

## Acceptance Criteria:

- After submitting a post, I,  as the post author, can see options to delete and update my post
- When I click the delete option, a confirmation prompt appears
- Upon deleting or editing my post, a success message is displayed

## Tasks:

- [ ] Create views and modify urls
- [ ] Update templates
- [ ] Add buttons, style
- [ ] Add JavaScript logic
