### ISSUE TITLE
22. User story: Manage "About" site

### ISSUE THREAD

**Issue by lienebriede** [lienebriede/jurtaka-hiking-forum#38]
As a **Site Admin** I can **manage the content on the About site** so that **I can provide up-to-date information to users**

## Acceptance Criteria:

- I can find the "About" page on the admin panel
- I can manage the text of the page
- I can style the text directly in the admin panel

## Tasks:

- [ ] Create a new app and a About model, register
- [ ] Create views and urls
- [ ] Modify templates
- [ ] Add Summernote to enhance the admin panel
