### ISSUE TITLE
User story: Navbar and footer

### ISSUE THREAD

**Issue by lienebriede** [lienebriede/jurtaka-hiking-forum#41]
As a **New Site User** I can **see a a navbar and a footer** so that **I can navigate the site and find additional information**

## Acceptance Criteria:

- The navbar section is positioned at the top of the page
- The footer section is positioned at the bottom of the page
- The navbar and footer design complements the overall design of the site
- The footer contains links to social media pages

## Tasks:

- [x] Create and style a navbar
- [x] Create and style a footer
- [x] Add social media links to footer
- [x] Design responsively
